// Questions Actions
export const LOAD_QUESTIONS_START = 'LOAD_QUESTIONS_START';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';


// Question Modal Actions
export const SHOW_MODAL_SUCCESS = 'SHOW_MODAL_SUCCESS';
export const TOGGLE_MODAL_SUCCESS = 'TOGGLE_MODAL_SUCCESS';
export const SELECT_EDIT_QUESTION = 'SELECT_EDIT_QUESTION';




