// Questions Actions
export const LOAD_QUESTIONS_START = 'LOAD_QUESTIONS_START';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const POST_ON_QUESTION_SUCCESS = 'POST_ON_QUESTION_SUCCESS';
export const DELETE_POST_ON_QUESTION_SUCCESS = 'DELETE_POST_ON_QUESTION_SUCCESS';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';
export const LOAD_QUESTIONS_BY_ID_START = 'LOAD_QUESTIONS_BY_ID_START';
export const LOAD_QUESTIONS_BY_ID_SUCCESS = 'LOAD_QUESTIONS_BY_ID_SUCCESS';
export const LIKE_UNLIKE_QUESTION_SUCCESS = 'LIKE_UNLIKE_QUESTION__SUCCESS';
export const SORT_QUESTIONS_SUCCESS = 'SORT_QUESTIONS_SUCCESS';
export const LIKE_UNLIKE_QUESTION_ANSWER_SUCCESS = 'LIKE_UNLIKE_QUESTION_ANSWER_SUCCESS';
export const CREATE_ANSWER_COMMENT_SUCCESS = 'CREATE_ANSWER_COMMENT_SUCCESS';
export const DELETE_POST_ON_ANSWER_SUCCESS = 'DELETE_POST_ON_ANSWER_SUCCESS';
export const EDIT_POST_ON_ANSWER_SUCCESS = 'EDIT_POST_ON_ANSWER_SUCCESS';

// Question Modal Actions
export const SHOW_MODAL_SUCCESS = 'SHOW_MODAL_SUCCESS';
export const TOGGLE_MODAL_SUCCESS = 'TOGGLE_MODAL_SUCCESS';
export const SELECT_EDIT_QUESTION = 'SELECT_EDIT_QUESTION';
export const SWAP_TAGS = 'SWAP_TAGS';
export const ADD_TAG = 'ADD_TAG';
export const DELETE_TAG = 'DELETE_TAG';
  
// User Actions
export const LOAD_USER_BY_ID_START = 'LOAD_USER_BY_ID_START';
export const LOAD_USER_BY_ID_SUCCESS = 'LOAD_USER_BY_ID_SUCCESS';

// Warning Modal Actions
export const SHOW_WARNING_SUCCESS = 'SHOW_WARNING_SUCCESS';
export const TOGGLE_WARNING_MODAL_SUCCESS = 'TOGGLE_WARNING_MODAL_SUCCESS';
export const WARNING_PROCEED_SUCCESS = 'WARNING_PROCEED_SUCCESS';
export const SET_WARNING_ACTIONS = 'SET_WARNING_ACTIONS';
export const SET_TEXT_SUCCESS = 'SET_TEXT_SUCCESS';

// Search Actions
export const LOAD_SEARCH_SUGGESTIONS_SUCCESS = 'LOAD_SEARCH_SUGGESTIONS_SUCCESS';
export const CLEAR_SEARCH_SUGGESTIONS_SUCCESS = 'CLEAR_SEARCH_SUGGESTIONS_SUCCESS';




